name = input('Digite algo: ')
print('O tipo desse valor: {}'.format(type(name)))
print('Só tem espaço? {}'.format(name.isspace()))
print('É um número? {}'.format(name.isalnum()))
print('É alfabético? {}'.format(name.isalpha()))
print('É alfanumérico? {}'.format(name.isalnum()))
print('Está em maiúsculas? {}'.format(name.isupper))
print('Está minúsculas? {}'.format(name.islower()))
print('Está capitalizada? {}'.format(name.istitle()))
